### ISSUE TITLE
Incorrect bullet to number list transition

### ISSUE THREAD

**Issue by MO-Movia** [MO-Movia/licit-fork#1]
[List bug.docx](https://github.com/MO-Movia/licit/files/4226379/List.bug.docx)
When having a bullet list that you want to convert to a numbered list with sub-bullets in it, selecting the list and then pressing the numbered list button will correct change the list to numbers, but the numbering isn't correct for items after sub-bullets.

**Comment by MO-Movia** [comment]
Apparently already fixed, the version that was hosted on the old CZI Prosemirror site wasn't running with the latest code base. Will stand up new demo server soon.

**Comment by firmusoft** [comment]
**Collaboration** not available.
