### ISSUE TITLE
Disable buttons when no text is selected

### ISSUE THREAD

**Issue by MO-Movia** [MO-Movia/licit-fork#10]
If you put the cursor anywhere in the text, but don't highlight it, things like Bold, Italics, text size/color/font, etc. are still active. They shouldn't be, because there is nothing selected to apply that style to. And you get strange behaviors. If you put the cursor on a line somewhere with text, but don't select the text, and then hit a font size much larger than you have, the line changes as those some piece of text in there is that size. As soon as you click somewhere else or move your cursor with the arrow keys, the line immediately fixes itself, but there was no reason to allow that to happen in the first place. If no next is selected, why have the buttons enabled?

**Comment by hedgerwang** [comment]
This works as expected.

Instead if asking user to select text then click "B" to make the text bold, user could click "B" first then start to type text in bold styles.

Google Doc has the same behavior.

**Comment by MO-Movia** [comment]
OK, understood. Closing as not an issue.
